version: '3.7'

services:
  postgres:
    build:
      context: ../
      dockerfile: docker/build/postgres.dockerfile
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    restart: on-failure
  application:
    build:
      context: ../
      dockerfile: docker/build/application.dockerfile
    ports:
      - 3000:3000
    env_file:
      - application.env
    depends_on:
      - postgres
    restart: on-failure
